name: freet
description: >-
  Plataforma m贸vil modular en Flutter para generaci贸n de rutinas inteligentes, evaluaci贸n
  con visi贸n por computador y experiencia social.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: 0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.4
  firebase_analytics: ^10.7.2
  firebase_remote_config: ^4.3.5
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1
  intl_phone_field: ^3.2.0
  tflite_flutter: ^0.10.0
  camera: ^0.10.5+9
  flutter_reactive_ble: ^5.0.3
  connectivity_plus: ^5.0.2
  either_dart: ^0.2.0
  equatable: ^2.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.7.4
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/animations/
